# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crud.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncrud.proto\"\x1d\n\rCreateRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\")\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x10\n\x0eUpdateResponse\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x10\n\x0e\x44\x65leteResponse2\xb3\x01\n\x0b\x43RUDService\x12)\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12)\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEREQUEST']._serialized_start=14
  _globals['_CREATEREQUEST']._serialized_end=43
  _globals['_CREATERESPONSE']._serialized_start=45
  _globals['_CREATERESPONSE']._serialized_end=73
  _globals['_READREQUEST']._serialized_start=75
  _globals['_READREQUEST']._serialized_end=100
  _globals['_READRESPONSE']._serialized_start=102
  _globals['_READRESPONSE']._serialized_end=130
  _globals['_UPDATEREQUEST']._serialized_start=132
  _globals['_UPDATEREQUEST']._serialized_end=173
  _globals['_UPDATERESPONSE']._serialized_start=175
  _globals['_UPDATERESPONSE']._serialized_end=191
  _globals['_DELETEREQUEST']._serialized_start=193
  _globals['_DELETEREQUEST']._serialized_end=220
  _globals['_DELETERESPONSE']._serialized_start=222
  _globals['_DELETERESPONSE']._serialized_end=238
  _globals['_CRUDSERVICE']._serialized_start=241
  _globals['_CRUDSERVICE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
